### ISSUE TITLE
game crashes on "bespin_platform" boss fight

### ISSUE THREAD

**Issue by n1mras** [xLAva/JediOutcastLinux#14]
Hi ive been playing through the game without much trouble so far, great job in getting it to run this well!.

On the level (according to save file) "bespin_platform" i started getting hit with game crashes. it happened twice during the level but seems to be reproducible during the "boss fight" against desann's apprentice because i cant get through it without it crashing. 

I can probably get past this by manually switching maps but i wanted to report it in case this problem isnt a local occurrence on my own system. 

I compiled and ran it with the (as of today) latest available source. commit c454e399f4ac2549c72770458aa4f7bad8a03d33

Active cheats: god mode

**Comment by lpolasek** [comment]
This is due a division by 0 on Q_irand (code/game/q_shared.h:724)

I will look at it in more detail when I have more time.

Regards...

**Comment by lpolasek** [comment]
Fixed on https://github.com/lpolasek/JediOutcastLinux/commit/3a6fc1433dbd9218e4326d62502f93c407feb7dc
Regards...

**Comment by n1mras** [comment]
yes, that worked, thank you very much! :D

Im not sure if its related but while running the boss encounter with your fix i noticed a change in her AI. She threw force powers like crazy. noticeably more so than before. since this function was a random nr generator perhaps it affected the probability outcome? im not knowledgeable enough to be of much help here but i thought it worth mentioning. ill run another test encounter with the old binary, perhaps it was just a fluke.

**Comment by lpolasek** [comment]
The outcome of Q_irand should be the same. I only rearranged the operation to avoid division by 0.
Tell us if this behavior continues.

Best regards...

**Comment by xLAva** [comment]
Your fix wasn't correct. Always min was used.
I changed it in the first place because on Linux MAX_RAND is int max -> so the calculation is always overfloating.
My fix (which is committed + new binary) handles the case when min and max is the same.
