### ISSUE TITLE
Can't remove console

### ISSUE THREAD

**Issue by Nordvind** [xLAva/JediOutcastLinux#17]
As in most Q3 engine-powered games, you can bring up console, by pressing '~' on keyboard. However, upon pressing it again, it doesn't disappear, as it usually does in other Q3-engined games. I've found only one way to remove it, by pressing 'Esc' to bring up game menu, and then returning to game, by pressing 'Esc' again.

Certainly, its not a critical issue :) But I find it slightly annoying. 

P.S. If I have time, I'll look into it myself as well.

**Comment by n1mras** [comment]
hi, try ctrl + z :) it brings up (or down) the console, something i found out by accident :P

**Comment by Nordvind** [comment]
Ctrl + z works, but I think issue is still there. Judging from the line `Cmd_AddCommand ("toggleconsole", Con_ToggleConsole_f);` in **cl_console.cpp** file, and lines `bind ` "toggleconsole"
bind ~ "toggleconsole"` from **jk2config.cfg**, intention was to use '`' or '~' to toggle console state, not Ctrl + z combination :) 

It seems that **Con_ToggleConsole_f** is called only once, when pressing '~' key, for some reason. And it's called every time, when pressing Ctrl + Z.

**Comment by lpolasek** [comment]
I fixed it on 93b44071add1efd1e348a9a250bcd1873e5a37d8. It will take CTRL-Z (hardcoded defaul) and also the keys binded in jk2config.cfg.

Please let me know any issue.

Best regards from Argentina...
