### ISSUE TITLE
Brightness slider does nothing

### ISSUE THREAD

**Issue by LiamDawe** [xLAva/JediOutcastLinux#26]
Has anyone else noticed that the brightness slider actually does nothing on this build?

I had to turn up the "gamma" setting manually in the config files to 1.6 to make things actually visible.

Edit > Okay so my request then is the hardware gamma support for Linux :)

**Comment by xLAva** [comment]
Actually that is not true.
The slider does change the gamma value, but the hardware gamma support is not yet implemented for Linux.

I'm not sure what makes the game brighter if you change the value (I think some default textures + fog is changed with the value on the renderer startup), but you can change the slider in the game and after a restart you get a brighter / darker in-game picture.

So no need to set it by hand - but you need to restart the game.

I'll have a look at a proper gamma control for Linux.

**Comment by LiamDawe** [comment]
I tried setting it to low and to high it didnt change gamma at all. I had to change it manually in the cfg file. Thts why ive done the readme bit.

**Comment by xLAva** [comment]
If you set the developer flag to 4 you see in the terminal output that the value is changed on slider movement.
But you only see a change in brightness if you restart the game completely and only in the levels.

I'm actually surprised the changed value does anything on Linux because the proper gamma support is not yet implemented.

**Comment by LiamDawe** [comment]
Infact you are right, I have to ramp it up, completely exit the game and then go back in - that's quite a pain.

**Comment by neko-kai** [comment]
> hardware gamma support is not yet implemented for Linux.

Then how does gamma control work under wine?

**Comment by xLAva** [comment]
I should have been clearer. Linux has some sort of gamma control but I didn't implement it yet in the Linux port.
It is on the TODO list.

**Comment by xLAva** [comment]
Basic gamma support was added in 9bf4eb919ec6293977e6567576f06f16b21afd2f

**Comment by LiamDawe** [comment]
That looks a bit dangerous to set the systems gamma?

**Comment by xLAva** [comment]
Yes it is NOT the best solution, but it is the only solution I found without reworking stuff deep in the original game (which I don't want to do).
All old games do it this way and this is an old game, so ...
I took this from the wine code, so if you play the windows version of the game with wine the same thing happens.
The best solution would be to handle this in a shader.

**Comment by LiamDawe** [comment]
Ah well if it's the same then fair enough!
