### ISSUE TITLE
Ubuntu Library Incompatabilities

### ISSUE THREAD

**Issue by ShaneQful** [xLAva/JediOutcastLinux#29]
On 64-bit Ubuntu 12.04 installation of libxxf86dga1:i386 causes the removal of 

```
Removing brasero ...
Removing ubuntu-desktop ...
Removing gnome-media ...
Removing gnome-session ...
Removing nautilus-share ...
Removing nautilus-sendto ...
Removing nautilus ...
Removing gvfs-fuse ...
Removing gvfs-backends ...
Removing gvfs ...
Removing gvfs-daemons ...
Removing xorg ...
Removing x11-utils ...
Removing libxxf86dga1 ...
```

which requires the user to reinstall them after playing the game or not be able to log in after a reboot.
#### Work around:

```
sudo apt-get install libxxf86dga1:i386
./jasp
sudo apt-get install libxxf86dga1:amd64
sudo apt-get install ubuntu-desktop
```

**Comment by xLAva** [comment]
Hi!
I removed the dependency for libxxf86dga1:i386.
Just grab the new binary.

**Comment by ShaneQful** [comment]
Thanks a million, your an absolute hero :)

**Comment by ShaneQful** [comment]
Sorry dude but it just segfaults now, with both me compiling it myself and with your binary any idea what it could be ? I can jump into the code my self but I rather have some direction if I'm going too.

**Comment by xLAva** [comment]
That sounds not good. Do you have any log files of the crash?

**Comment by xLAva** [comment]
Oh - and try to compile the binary with -g (debug symbols) - you might get a stacktrace on the crash.

**Comment by ShaneQful** [comment]
Pulled from the repo today with intent to fix the issue but the game just worked like a charm. Thanks again for doing the port :)
