### ISSUE TITLE
Mod support?

### ISSUE THREAD

**Issue by dschneider** [xLAva/JediOutcastLinux#30]
I just tried to install the Bloody Dismemberment mod (http://jediknight3.filefront.com/file/Bloody_Dismemberment;81937). I copied the .pk3 file into the /base directory, but in-game there no visible changes. I do the same in Windows and it works flawlessly. Are there differences when loading .pk3 files?

**Comment by dschneider** [comment]
I played around further and it turns out you have to rename the file to "assets4.pk3" for example so that it loads it correctly. In Windows you can just leave the file name as is. Is this considered an issue?

**Comment by xLAva** [comment]
Hmm. Thx for the report. I will have a look at it tomorrow.

**Comment by xLAva** [comment]
The bug is fixed. I made the file sorting case insensitive. 
The code is committed. I'll make a new binary tonight.
