### ISSUE TITLE
failed to compile under linux-64bit

### ISSUE THREAD

**Issue by WieselTrupp** [xLAva/JediOutcastLinux#31]
i cant compile this game under Archlinux 64bit.
it built and ran very good under Archlinux 32bit.

-- The C compiler identification is GNU 4.8.0
-- The CXX compiler identification is GNU 4.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux
Scanning dependencies of target jk2gamex86
[  0%] Building CXX object CMakeFiles/jk2gamex86.dir/code/cgame/FX_ATSTMain.cpp.o
In file included from /usr/include/c++/4.8.0/bits/stl_algo.h:59:0,
                 from /usr/include/c++/4.8.0/algorithm:62,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/../game/../icarus/Sequencer.h:18,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/../game/../icarus/icarus.h:28,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/../game/g_shared.h:7,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/cg_local.h:10,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/cg_headers.h:3,
                 from /home/wesley/packete/jedioutcastlinux-git/src/JediOutcastLinux/code/cgame/FX_ATSTMain.cpp:4:
/usr/include/c++/4.8.0/cstdlib:178:10: Fehler: expected unqualified-id before »__int128«
   inline __int128
          ^
make[2]: **\* [CMakeFiles/jk2gamex86.dir/code/cgame/FX_ATSTMain.cpp.o] Fehler 1
make[1]: **\* [CMakeFiles/jk2gamex86.dir/all] Fehler 2
make: **\* [all] Fehler 2

**Comment by lpolasek** [comment]
This is due to your 64bit compilation.

Here are some clues on the problem:
https://github.com/Razish/OpenJK/pull/34#issuecomment-16016860
http://stackoverflow.com/questions/15725167/int128-error-when-compiling-32-bit

Try removing -m32 from CMAKE_C_FLAGS_RELEASE and CMAKE_CXX_FLAGS_RELEASE from CMakeLists.txt.

Hope its helps, regards...

**Comment by WieselTrupp** [comment]
thank you very much, the link helped.

i dont need to tinker with the CMakeLists.txt, all that was missing was gcc-multilib.
game compiles and runs fine for me now

**Comment by lpolasek** [comment]
Great to hear that :+1:  

Best regards...
