### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by jarenere** [xLAva/JediOutcastLinux#32]
Hi, thanks for the linux port

I can see in the photos plus.google that the characters have shadows but I don't see in my game

I have select:
- Detailed Sahders: on
- Dinamic lights: on
- Shadow: volumetric

other information: 

GL_VENDOR: Intel Open Source Technology Center
GL_RENDERER: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2
GL_VERSION: 2.1 Mesa 9.1.1
GL_MAX_TEXTURE_SIZE: 8192
GL_MAX_ACTIVE_TEXTURES_ARB: 8 

I use arch linux 64bits, and I used the latest version of git https://aur.archlinux.org/packages/jedioutcastlinux-git/

**Comment by xLAva** [comment]
Your shadow settings look ok.
Please post your startup log info (start the game in a terminal to get that).
Maybe your card doesn't support a OpenGL extension or the driver has an issue.

**Comment by jarenere** [comment]
http://pastebin.com/1Cin7pWy

**Comment by xLAva** [comment]
Hmm - the log output looks normal to me.
It might be a driver issue. This is hard to fix without the hardware.
On my Intel card the shadows just work.

Sorry I can't help with that.

**Comment by jarenere** [comment]
Thanks anyway

PS: If I select shadow simple, there are a round shadow below the characters. Better than nothing, xD

**Comment by xLAva** [comment]
The simple shadows look sometimes better than the volume shadow. So it should not be a big deal.
:-)
