### ISSUE TITLE
problem with mouse with latest binary (3a4ddf4b8302c05907d1541222bc9729553cf80a)

### ISSUE THREAD

**Issue by zukka77** [xLAva/JediOutcastLinux#33]
Mouse doesn't move well using latest binaries, it jumps and get stuck, no problem with previous version 0b6f814eca51e02a0cd20ee8b64359078f5fbbf7 .
Even if I have to restart gnome-shell every time i exit the game, the game is playable :)

**Comment by xLAva** [comment]
The dga mouse support was removed because of some dependencies issues.
I'll check for a solution to bring it back in the build.

**Comment by xLAva** [comment]
The dga mouse support is back with 0a3cea0a78f605db1c6a14ad9d9284f70e3e61a1. It is loaded dynamic so there should be no dependency issues anymore.
