### ISSUE TITLE
Stuck in Level 4 ... can't move or shoot

### ISSUE THREAD

**Issue by xLAva** [xLAva/JediOutcastLinux#4]
Don't know where this is coming from, but I can't move or shoot in the beginning of Level 4.

**Comment by z0id** [comment]
Indeed. I tried noclip, but it didn't move.
I tried skipping the level with

> devmapall
> map artus_topside

but I couldn't move there either.
UPDATE: I started a new game, then changed map to artus_topside and I could move.

**Comment by n1mras** [comment]
ty for the workaround. I'm also experiencing the same problem.

**Comment by xLAva** [comment]
It is fixed now. Load a savegame from the previous level and you should be fine.
