### ISSUE TITLE
game crash immediately

### ISSUE THREAD

**Issue by Micha-Btz** [xLAva/JediOutcastLinux#41]
~/media/games/jedioutcast$ ./jk2sp 
~/media/games/jedioutcast$ ./jk2sp 
JK2: v1.03 linux-i386 Aug  4 2013
Initialising zone memory .....
----- FS_Startup -----
Current search path:
/home/mdomann/.jk2/base
./base/assets1.pk3 (8011 files)
./base/assets0.pk3 (6674 files)
./base

---

14685 files in pk3 files
execing default.cfg
execing jk2config.cfg
couldn't exec autoexec.cfg
----- Client Initialization -----
## ----- CL_Shutdown -----

Error: Could not open string package 'KEYNAMES'

Debian Sid
dpkg -l|grep libopenal
ii  libopenal-data                                              1:1.14-4                           all          Software implementation of the OpenAL API (data files)
ii  libopenal-dev:amd64                                         1:1.14-4                           amd64        Software implementation of the OpenAL API (development files)
ii  libopenal1:amd64                                            1:1.14-4                           amd64        Software implementation of the OpenAL API (shared library)
ii  libopenal1:i386                                             1:1.14-4                           i386         Software implementation of the OpenAL API (shared library)

Any suggestions?
thanks for porting the games. Micha

**Comment by jamie-marchant** [comment]
It appears you need to install the game using Wine and then upgrade to 
version 1.4 before it will work.
On 01/04/2014 02:10 PM, Micha-Btz wrote:

> ~/media/games/jedioutcast$ ./jk2sp
> ~/media/games/jedioutcast$ ./jk2sp
> JK2: v1.03 linux-i386 Aug 4 2013
> Initialising zone memory .....
> ----- FS_Startup -----
> Current search path:
> /home/mdomann/.jk2/base
> ./base/assets1.pk3 (8011 files)
> ./base/assets0.pk3 (6674 files)
> ./base
> 
> ---
> 
> 14685 files in pk3 files
> execing default.cfg
> execing jk2config.cfg
> couldn't exec autoexec.cfg
> ----- Client Initialization -----
> 
> ```
> ----- CL_Shutdown -----
> ```
> 
> Error: Could not open string package 'KEYNAMES'
> 
> Debian Sid
> dpkg -l|grep libopenal
> ii libopenal-data 1:1.14-4 all Software implementation of the OpenAL 
> API (data files)
> ii libopenal-dev:amd64 1:1.14-4 amd64 Software implementation of the 
> OpenAL API (development files)
> ii libopenal1:amd64 1:1.14-4 amd64 Software implementation of the 
> OpenAL API (shared library)
> ii libopenal1:i386 1:1.14-4 i386 Software implementation of the OpenAL 
> API (shared library)
> 
> Any suggestions?
> thanks for porting the games. Micha
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xLAva/JediOutcastLinux/issues/41.

## 

-Jamie Marchant

**Comment by Micha-Btz** [comment]
after updateto 1.04  it work.
