### ISSUE TITLE
Running ./jk2sp gives "Error: Corrupted pk3: 1765859889"

### ISSUE THREAD

**Issue by D8174** [xLAva/JediOutcastLinux#42]
I'm sure this is a bug because with OpenJK (JK2), it works fine with the same pk3's.

**Comment by D8174** [comment]
@xLAva I don't want to start a new issue for this but how is MP coming along? I don't know of another project which has JK2 MP working.

**Comment by xLAva** [comment]
What about OpenJK - I think they are working on a Linux MP port.
I have no plans at the moment to port MP myself.

**Comment by D8174** [comment]
They have JKA SP and MP, and JK2 SP. I don't think they have plans to port it either.

**Comment by xLAva** [comment]
I didn't know that. I can't promise anything but I will have a look at it in the future.

**Comment by D8174** [comment]
Thanks, I appreciate it.

**Comment by D8174** [comment]
So this is only slightly relevant to our discussion, but https://github.com/ioquake/jedi-outcast has a working multiplayer. The problem for me is that I can't even change the resolution or it segfaults. I'm stuck at 640x480. I would give them a stack trace but they have issues disabled. :/
