### ISSUE TITLE
Invalid Link for 1.04 Patch!!!

### ISSUE THREAD

**Issue by C1995** [xLAva/JediOutcastLinux#45]
For the 1.04 patch/update for non-steam users the url: http://www.lucasarts.com/support/update/jedioutcast2.html is invalid as Disney has revamped the site. The new url however is: http://help.starwars.com/articles/en_US/FAQ/Where-do-I-find-the-latest-patch-for-Jedi-Knight-II-Jedi-Outcast?section=Star-Warsv and then a download link on the page.

**Comment by xLAva** [comment]
Thx for this information. I will change the readme tonight!

**Comment by xLAva** [comment]
Done
