### ISSUE TITLE
Ubuntu 14.04 LTS support 

### ISSUE THREAD

**Issue by vastsoun** [xLAva/JediOutcastLinux#46]
Hey guys!

I followed the instructions in the following link to install PlayOnLinux and to get the game working:
http://www.gamersonlinux.com/forum/threads/jedi-knight-ii-jedi-outcast-guide.617/

However, when executing the ..../Release/jk2sp the following error occurs:

$ ./jk2sp 
./jk2sp: error while loading shared libraries: libopenal.so.1: cannot open shared object file: No such file or directory

I soft linked the libopal.so.1 in /user/lib/x86_64-linux-gnu/libopenal.so.1 and then an error hit regarding the type of ELF file. I think it might be a 64bit issue since my system is a 64bit Ubuntu 14.04 LTS.

Has anyone got it to work on 64bit 14.04? If not, I just might look into porting it if given some direction. I have experience with cmake, gcc/g++ etc. I just need some info regarding the build configuration/flags etc and whatever else might be needed.

Cheers,

Vassilis.

**Comment by vastsoun** [comment]
I just may of spoke too soon about needing to port. I got it to work!

If you install steam, then the i386 version of libopenal.so.1 is installed already. I did a super dirty work around by soft linking that instead:

$ sudo ln -s /home/vassilis/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libopenal.so.1 libopenal.so.1

and then continued with the instructions in the aforementioned link and presto!

Just replace "vassilis" in the path with your user name and it should work.

Cheers guys.

**Comment by xLAva** [comment]
Or you could just install the 32 bit version of OpenAL.
sudo apt-get install libopenal1:i386

It was included in the other package you had to install on 12.04 64 bit.

It looks like it is different on 14.04.
I will update the readme.

Thx for the issue report.
