### ISSUE TITLE
Not starting on 13.04

### ISSUE THREAD

**Issue by ghost** [xLAva/JediOutcastLinux#5]
on 13.04, even copying the base folder from the original game it won't start. This is the output:
JK2: v1.03 linux-i386 Apr 15 2013
Initialising zone memory .....
----- FS_Startup -----
Current search path:
/home/xxx/Downloads/JediOutcastLinux-JediOutcastLinux/code/Release/base

---

0 files in pk3 files
Error: Invalid product identification

**Comment by xLAva** [comment]
Please post the directory entries of 
/home/sartor/Downloads/JediOutcastLinux-JediOutcastLinux/code/Release/base

with information about the file access rights would be great.
ls -l

**Comment by ghost** [comment]
I thought I had removed my username from the copied text before...

total 40
-r--r--r-- 1 xxx xxx 2178 apr  3 16:07 default.cfg
drwxrwxr-x 4 xxx xxx 4096 apr  3 16:07 ext_data
-r--r--r-- 1 xxx xxx  332 apr  3 16:07 high.cfg
-r--r--r-- 1 xxx xxx  368 apr  3 16:07 low.cfg
-r--r--r-- 1 xxx xxx  325 apr  3 16:07 med.cfg
-r--r--r-- 1 xxx xxx 2845 apr  3 16:07 mpdefault.cfg
-r--r--r-- 1 xxx xxx   68 apr  3 16:07 noMotion.cfg
-r--r--r-- 1 xxx xxx  165 apr  3 16:07 productid.txt
-r--r--r-- 1 xxx xxx   88 apr  3 16:07 restoreMotion.cfg
-r--r--r-- 1 xxx xxx  160 apr  3 16:07 vssver.scc

**Comment by xLAva** [comment]
ok - I think I know your problem.
Did you extract the assets*.pk3 files?
Don't do that. The game wants this special zip files.

My base folder looks like this:

drwxrwxr-x 3 xxx xxx 4,0K Apr 16 20:56 .
drwxr-xr-x 6 xxx xxx 4,0K Apr 16 23:22 ..
-rw-rw-r-- 1 xxx xxx 511M Apr  8 22:20 assets0.pk3
-rw-rw-r-- 1 xxx xxx  83M Apr  8 22:20 assets1.pk3
-rw-rw-r-- 1 xxx xxx 3,6M Apr  8 22:20 assets2.pk3
-rw-rw-r-- 1 xxx xxx 538K Apr  8 22:20 assets5.pk3
-rw-rw-rw- 1 xxx xxx 5,1K Apr 16 23:22 jk2config.cfg
-rw-rw-r-- 1 xxx xxx 9,3K Apr  8 22:20 jk2mpconfig.cfg

**Comment by ghost** [comment]
I'll try it tomorrow and tell you but that could be the answer...is it possible to use the files from the source code that was released a few days ago?

**Comment by xLAva** [comment]
I tested it on 13.04. Works normal so I close this bug report.
