### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by monreal** [xLAva/JediOutcastLinux#64]
Trying to build the game on Fedora 26, I get the following:

$ cmake ../code
-- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Used Settings: Ovr0.5=0 Ovr0.8=0 Ovr1=1 OvrStatic=0 OpenHMD=0
system name: Linux
Detected platform: Win32=0 MacOS=0 Linux=1
EXTERNAL_LIB_PATH=/home/micmon/code/gaming/JediAcademyLinux.git/code/../3rdparty
Build Type: RELEASE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/micmon/code/gaming/JediAcademyLinux.git/build

...

[ 34%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_misc.cpp.o
[ 34%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_misc_model.cpp.o
[ 34%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_missile.cpp.o
[ 34%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_mover.cpp.o
[ 35%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_nav.cpp.o
[ 35%] Building CXX object CMakeFiles/jagamehmdx86.dir/game/g_navigator.cpp.o
In file included from /home/micmon/code/gaming/JediAcademyLinux.git/code/game/../Ragl/graph_vs.h:106:0,
                 from /home/micmon/code/gaming/JediAcademyLinux.git/code/game/g_navigator.cpp:45:
/home/micmon/code/gaming/JediAcademyLinux.git/code/game/../Ragl/../Ratl/map_vs.h: In member function ‘ratl::set_base<T, IS_MULTI>::const_iterator ratl::set_base<T, IS_MULTI>::begin() const’:
/home/micmon/code/gaming/JediAcademyLinux.git/code/game/../Ragl/../Ratl/map_vs.h:1103:16: error: invalid use of ‘class ratl::set_base<T, IS_MULTI>::const_iterator’
   return this->const_iterator(this, this->front());
                ^~~~~~~~~~~~~~
/home/micmon/code/gaming/JediAcademyLinux.git/code/game/../Ragl/../Ratl/map_vs.h: In member function ‘ratl::set_base<T, IS_MULTI>::const_iterator ratl::set_base<T, IS_MULTI>::rbegin() const’:
/home/micmon/code/gaming/JediAcademyLinux.git/code/game/../Ragl/../Ratl/map_vs.h:1111:16: error: invalid use of ‘class ratl::set_base<T, IS_MULTI>::const_iterator’
   return this->const_iterator(this, this->back());
                ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/jagamehmdx86.dir/build.make:2991: CMakeFiles/jagamehmdx86.dir/game/g_navigator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/jagamehmdx86.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by xLAva** [comment]
You posted it on the wrong project. I fixed it anyway :-)
You should be able to compile JediAcademyLinux (HmdSupportDK2 branch).
https://github.com/xLAva/JediAcademyLinux/commit/5d601e66ebc215d22e40df049061002699c61813

**Comment by monreal** [comment]
Thanks!
