### ISSUE TITLE
error compilation on Ubuntu

### ISSUE THREAD

**Issue by legluondunet** [xLAva/JediOutcastLinux#66]
Hello,

If I try to compile JOL, compilation failed :
$ git clone https://github.com/xLAva/JediOutcastLinux.git
$ cd JediOutcastLinux
$ mkdir Build
$ cd Build
$ cmake ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
system name: Linux
Detected platform: Win32=0 MacOS=0 Linux=1
Build Type: RELEASE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/legluondunet/Bureau/JediOutcastLinux/JediOutcastLinux
$ make
Scanning dependencies of target jk2gamex86
[  0%] Building CXX object CMakeFiles/jk2gamex86.dir/code/qcommon/tri_coll_test.cpp.o
In file included from /usr/include/c++/7/math.h:36:0,
                 from /home/legluondunet/Bureau/JediOutcastLinux/JediOutcastLinux/code/qcommon/../game/../game/q_shared.h:35,
                 from /home/legluondunet/Bureau/JediOutcastLinux/JediOutcastLinux/code/qcommon/../game/common_headers.h:6,
                 from /home/legluondunet/Bureau/JediOutcastLinux/JediOutcastLinux/code/qcommon/tri_coll_test.cpp:16:
/usr/include/c++/7/cmath:41:10: fatal error: bits/c++config.h: Aucun fichier ou dossier de ce type
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/jk2gamex86.dir/build.make:62 : la recette pour la cible « CMakeFiles/jk2gamex86.dir/code/qcommon/tri_coll_test.cpp.o » a échouée
make[2]: *** [CMakeFiles/jk2gamex86.dir/code/qcommon/tri_coll_test.cpp.o] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/jk2gamex86.dir/all » a échouée
make[1]: *** [CMakeFiles/jk2gamex86.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Thank you for your help.

JOL git 8 october 2017
Config:
Ubuntu 17.10 Artful Aardvark 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 384.90 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by xLAva** [comment]
Hi!
Did you follow the instructions in BUILD.md?

It looks like you did not install the 32bit compile environment:

sudo apt-get install libsdl2-dev:i386 libglm-dev libopenal-dev:i386
sudo apt-get install cmake g++-multilib

**Comment by legluondunet** [comment]
ooops! Sorry I did read too quickly Buil.md, I didn't understand I have to  install the 32bits libraries.
No plan to have a 64 bits executable?

**Comment by xLAva** [comment]
I have no plans on doing a 64 bit port yet. I might do it some time in the future, but I'm not sure I will have time for it.
