### ISSUE TITLE
Crashes with "Error: Could not open string package 'KEYNAMES'"

### ISSUE THREAD

**Issue by marcusmoller** [xLAva/JediOutcastLinux#7]
I've moved everything as according to the readme, but the game crashes with the following error:
"Error: Could not open string package 'KEYNAMES'"

I'm running ArchLinux x64.

The full terminal output is:
[marcus@archlinux-desktop Release]$ ./jk2sp 
JK2: v1.03 linux-i386 Apr 15 2013
Initialising zone memory .....
 ----- FS_Startup -----
Current search path:
/home/marcus/GAMES/jedi2outcast/JediOutcastLinux/code/Release/base/assets1.pk3 (8011 files)
/home/marcus/GAMES/jedi2outcast/JediOutcastLinux/code/Release/base/assets0.pk3 (6674 files)
/home/marcus/GAMES/jedi2outcast/JediOutcastLinux/code/Release/base

---

14685 files in pk3 files
execing default.cfg
couldn't exec jk2config.cfg
couldn't exec autoexec.cfg
----- Client Initialization -----
----- CL_Shutdown -----

---

Error: Could not open string package 'KEYNAMES'

**Comment by xLAva** [comment]
This error is caused if you don't use the version 1.04.

For those not having the Steam version: you'll need the 1.04 update from here http://www.lucasarts.com/support/update/jedioutcast2.html

**Comment by Gnurfos** [comment]
Hi,

Just a question. That update seems to be provided as an exe file. Is the only solution to execute it via wine (or a windows install) ?

Thanks

**Comment by marcusmoller** [comment]
@Gnurfos:

I had to do so, which also required me to install the main game in WINE beforehand.

**Comment by Gnurfos** [comment]
I was a bit a disturbed by the need to use wine/windows before being able to play a native version, so I tried, and it seems to work if you just copy files assets2.pk3 and assets5.pk3 from a patched install. (I only went as far as playing a few minutes).

Those files are not so big, but I guess it's illegal to include them in this repository ?

**Comment by bjoern-tantau** [comment]
For anyone else with this problem, the required files are available at https://github.com/emileb/OpenGames/tree/master/jk2/src/main/assets.
