### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Metalhead33** [xLAva/JediOutcastLinux#71]
Console output:

> JK2: v1.03.01 linux-i386 Dec 29 2017
> Initialising zone memory .....
> ----- FS_Startup -----
> Current search path:
> /home/metalhead33/.jk2/base
> ./base/sdl_asset.pk3 (3 files)
> ./base/assets5.pk3 (4 files)
> ./base/assets2.pk3 (289 files)
> ./base/assets1.pk3 (8011 files)
> ./base/assets0.pk3 (6674 files)
> ./base
> 
> ----------------------
> 14981 files in pk3 files
> execing default.cfg
> execing jk2config.cfg
> execing autoexec.cfg
> ----- Client Initialization -----
> ----- Initializing Renderer ----
> -------------------------------
> ----- R_Init -----
> Initializing OpenGL subsystem
> ...loading libGL.so.1: ...initializing QGL
> succeeded
> Initializing OpenGL display
> ...setting mode -1:
>  1360 768
> Create Window 1360x768 at 536805376x536805376
> set relative mouse.Using 8/8/8 Color bits, 24 depth, 0 stencil display.
> Initializing OpenGL extensions
> ...GL_S3_s3tc available
> ...GL_EXT_texture_compression_s3tc available
> ...no tc preference specified
> .....using GL_EXT_texture_compression_s3tc
> ...using GL_EXT_texture_env_add
> ...Using GL_EXT_texture_edge_clamp
> ...using GL_ARB_multitexture
> ...using GL_EXT_compiled_vertex_array
> Opened Joystick 0
> Number of Axes: 2
> Number of Buttons: 10
> Number of Balls: 0
> Name: GreenAsia Inc.      USB  Joystick  
> 
> GL_VENDOR: NVIDIA Corporation
> GL_RENDERER: GeForce GTX 960/PCIe/SSE2
> GL_VERSION: 4.6.0 NVIDIA 387.34
> GL_MAX_TEXTURE_SIZE: 16384
> GL_MAX_ACTIVE_TEXTURES_ARB: 4
> 
> PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
> MODE: -1, 1360 x 768 fullscreen hz:N/A
> GAMMA: software w/ 0 overbright bits
> CPU: generic
> rendering primitives: single glDrawElements
> texturemode: GL_LINEAR_MIPMAP_LINEAR
> picmip: 1
> texture bits: 0
> lightmap texture bits: 0
> multitexture: enabled
> compiled vertex arrays: enabled
> texenv add: enabled
> compressed textures: enabled
> compressed lightmaps: disabled
> texture compression method: GL_EXT_texture_compression_s3tc
> anisotropic filtering: disabled
> Initializing Shaders
> ----- finished R_Init -----
> 
> ------- sound initialization -------
> OpenAL vendor string: OpenAL Community
> OpenAL renderer string: OpenAL Soft
> OpenAL version string: 1.1 ALSOFT 1.18.2
> ----- Sound Info -----
> sound system is muted
>    -1 stereo
>     0 samples
>     0 samplebits
>     0 submission_chunk
>     0 speed
> 0x0 dma buffer
> No background file.
> ----------------------
> ------------------------------------
> 
> --- ambient sound initialization ---
> Sound memory manager started
> UI menu load time = 273 milli seconds
> ----- Client Initialization Complete -----
> --- Common Initialization Complete ---
> ----- CL_Shutdown -----
> RE_Shutdown( 1 )
> Shutting down OpenGL subsystem
> ...shutting down QGL
> ...unloading OpenGL DLL
> -----------------------
> ➜  GameData ./jk2sp         
> JK2: v1.03.01 linux-i386 Dec 29 2017
> Initialising zone memory .....
> ----- FS_Startup -----
> Current search path:
> /home/metalhead33/.jk2/base
> ./base/sdl_asset.pk3 (3 files)
> ./base/assets5.pk3 (4 files)
> ./base/assets2.pk3 (289 files)
> ./base/assets1.pk3 (8011 files)
> ./base/assets0.pk3 (6674 files)
> ./base
> 
> ----------------------
> 14981 files in pk3 files
> execing default.cfg
> execing jk2config.cfg
> execing autoexec.cfg
> ----- Client Initialization -----
> ----- Initializing Renderer ----
> -------------------------------
> ----- R_Init -----
> Initializing OpenGL subsystem
> ...loading libGL.so.1: ...initializing QGL
> succeeded
> Initializing OpenGL display
> ...setting mode -1:
>  1360 768
> Create Window 1360x768 at 536805376x536805376
> set relative mouse.Using 8/8/8 Color bits, 24 depth, 0 stencil display.
> Initializing OpenGL extensions
> ...GL_S3_s3tc available
> ...GL_EXT_texture_compression_s3tc available
> ...no tc preference specified
> .....using GL_EXT_texture_compression_s3tc
> ...using GL_EXT_texture_env_add
> ...Using GL_EXT_texture_edge_clamp
> ...using GL_ARB_multitexture
> ...using GL_EXT_compiled_vertex_array
> Opened Joystick 0
> Number of Axes: 2
> Number of Buttons: 10
> Number of Balls: 0
> Name: GreenAsia Inc.      USB  Joystick  
> 
> GL_VENDOR: NVIDIA Corporation
> GL_RENDERER: GeForce GTX 960/PCIe/SSE2
> GL_VERSION: 4.6.0 NVIDIA 387.34
> GL_MAX_TEXTURE_SIZE: 16384
> GL_MAX_ACTIVE_TEXTURES_ARB: 4
> 
> PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
> MODE: -1, 1360 x 768 fullscreen hz:N/A
> GAMMA: software w/ 0 overbright bits
> CPU: generic
> rendering primitives: single glDrawElements
> texturemode: GL_LINEAR_MIPMAP_LINEAR
> picmip: 1
> texture bits: 0
> lightmap texture bits: 0
> multitexture: enabled
> compiled vertex arrays: enabled
> texenv add: enabled
> compressed textures: enabled
> compressed lightmaps: disabled
> texture compression method: GL_EXT_texture_compression_s3tc
> anisotropic filtering: disabled
> Initializing Shaders
> ----- finished R_Init -----
> 
> ------- sound initialization -------
> OpenAL vendor string: OpenAL Community
> OpenAL renderer string: OpenAL Soft
> OpenAL version string: 1.1 ALSOFT 1.18.2
> ----- Sound Info -----
> sound system is muted
>    -1 stereo
>     0 samples
>     0 samplebits
>     0 submission_chunk
>     0 speed
> 0x0 dma buffer
> No background file.
> ----------------------
> ------------------------------------
> 
> --- ambient sound initialization ---
> Sound memory manager started
> UI menu load time = 255 milli seconds
> ----- Client Initialization Complete -----
> --- Common Initialization Complete ---
> ----- CL_Shutdown -----
> RE_Shutdown( 1 )
> Shutting down OpenGL subsystem
> ...shutting down QGL
> ...unloading OpenGL DLL
> -----------------------

autoexec.cfg:

> seta r_mode -1
> seta r_customwidth "1360"
> seta r_customheight "768"
> seta cg_fov 90
> seta s_UseOpenAL "1"
> seta s_khz "48"
> seta r_stereo "1"

Setting the audio to the default 22khz, s_UseOpenAL "0" or  r_stereo "0" did not help either. Also, my Jack sound system is producing Xruns when the game is on.

I am on Gentoo Linux, Kernel version 4.14.8-r1. SDL2 2.0.7, Openal Soft 1.18.2, Alsa Lib 1.1.4.1, PulseAudio 11.1, Jack 1.9.10.

**Comment by xLAva** [comment]
It looks like this bug might be related to your issue #68.
I don't have Gentoo running, but I will poke you once I fixed #68 to re-test on your setup.

**Comment by Metalhead33** [comment]
I solved it by changing some settings in OpenAL soft, forcing it to use the PulseAudio backend instead of the JACK backend, and making it run with a fixed sample rate.
