### ISSUE TITLE
Recenter View

### ISSUE THREAD

**Issue by FolkSong** [xLAva/JediOutcastLinux#72]
Is there a way to manually map a button to reset VR view? I play standing and the gun will drift away from me as I'm turning around.

You mention in another post that a button should be mapped by default, but it doesn't work for me on an Xbox One controller (I tried every button). I have the same issue in Jedi Academy, even after installing the extra "assets4.pk3" file. The controls work fine otherwise.

**Comment by xLAva** [comment]
I think once your settings are saved in the base folder file jk2config.cfg, the new assets4.pk3 does not recreate the added setting.

So you could just delete your user settings, or better just add the recenter binding to it:
`bind JOY6 "hmdrecenter"`
in jk2config.cfg

**Comment by FolkSong** [comment]
That's exactly what I was looking for, thanks.
