### ISSUE TITLE
Unclear how to start touch controllers

### ISSUE THREAD

**Issue by udwxmoose** [xLAva/JediOutcastLinux#75]
Hi, got VR to work, but I do not know how to enabled the hand tracked controllers on the touch-vr build

**Comment by xLAva** [comment]
You need of course to build it yourself for now (if you not already did that).
(I hope I have a new experimental build ready next week).

Because of the still experimental state of the touch support you have to enabled it by adding/changing this value in your jk2config.cfg:
hmd_useHands 1

**Comment by Midnightmaster** [comment]
Hi everyone!

My touch controllers (Oculus) do not work, only Xbox controller. Neither movement/motion nor buttons. hmd_unseHand has the value 1. Does anyone have an idea?
Thank you!

This is my jk2config.cfg:
// generated by Star Wars Jedi Outcast, do not modify
unbindall
bind SHIFT "+speed"
bind CTRL "+use"
bind ALT "+altattack"
bind TAB "datapad"
bind ENTER "invuse"
bind KP_PGDN "use_seeker"
bind KP_LEFTARROW "use_lightamp_goggles"
bind KP_5 "use_sentry"
bind F1 "force_throw"
bind F2 "force_pull"
bind F3 "force_speed"
bind F4 "force_distract"
bind SPACE "+moveup"
bind , "+moveleft"
bind - "weapon 0"
bind . "+moveright"
bind / "+mlook"
bind 0 "weapon 10"
bind 1 "weapon 1"
bind 2 "weapon 2"
bind 3 "weapon 3"
bind 4 "weapon 4"
bind 5 "weapon 5"
bind 6 "weapon 6"
bind 7 "weapon 7"
bind 8 "weapon 8"
bind 9 "weapon 9"
bind A "+moveleft"
bind B "use_bacta"
bind C "+movedown"
bind D "+moveright"
bind E "+use"
bind F "+useforce"
bind G "zoom"
bind L "saberAttackCycle"
bind M "datapad"
bind P "cg_thirdperson !"
bind Q "weapprev"
bind R "weapnext"
bind S "+back"
bind V "+strafe"
bind W "+forward"
bind X "forcenext"
bind Z "forceprev"
bind [ "invprev"
bind \ "weapongrabbed"
bind ] "invnext"
bind ` "toggleconsole"
bind ~ "toggleconsole"
bind F5 "force_heal"
bind F6 "+force_grip"
bind F7 "+force_lightning"
bind MWHEELUP "weapprev"
bind MWHEELDOWN "weapnext"
bind MOUSE1 "+attack"
bind MOUSE2 "+altattack"
bind PGUP "+lookup"
bind F9 "load quik"
bind F10 "uimenu ingameloadmenu"
bind F11 "uimenu ingamesavemenu"
bind F12 "save quik*"
bind END "centerview"
bind PGDN "+lookdown"
bind MOUSE3 "zoom"
bind UPARROW "+forward"
bind DOWNARROW "+back"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
seta d_slowmodeath "3"
seta g_saberAutoAim "1"
seta g_saberAnimSpeed "1"
seta g_saberMoveSpeed "1"
seta g_saberRealisticCombat "0"
seta g_saberAutoBlocking "1"
seta g_subtitles "2"
seta g_dismemberProbabilities "1"
seta cg_reliableAnimSounds "1"
seta cg_missionInfoCentered "1"
seta cg_gunAutoFirst "1"
seta cg_saberAutoThird "1"
seta cg_bobroll "0.002"
seta cg_bobpitch "0.002"
seta cg_bobup "0.005"
seta cg_runroll "0.005"
seta cg_runpitch "0.002"
seta cg_simpleItems "0"
seta cg_crosshairY "0"
seta cg_crosshairX "0"
seta cg_crosshairSize "24"
seta cg_crosshairIdentifyTarget "1"
seta cg_dynamicCrosshair "1"
seta cg_drawAmmoWarning "1"
seta cg_drawSnapshot "0"
seta cg_drawFPS "0"
seta cg_drawTimer "0"
seta cg_drawStatus "1"
seta cg_draw2D "1"
seta cg_stereoSeparation "0.4"
seta cg_drawGun "1"
seta cm_playerCurveClip "1"
seta cg_crosshairForceHint "1"
seta g_spskill "1"
seta g_dismemberment "0"
seta ui_iscensored "1"
seta r_fakeFullscreen "0"
seta hmd_allowdummydevice "0"
seta hmd_forceLibrary ""
seta hmd_enabled "1"
seta cg_shadows "1"
seta hmd_useHands "1"
seta cg_hudFiles "ui/jk2hud.txt"
seta ui_bigFont "0.4"
seta ui_smallFont "0.25"
seta ui_menuFiles "ui/menus.txt"
seta cg_marks "1"
seta cg_drawCrosshair "1"
seta ff_delay "40"
seta ff_channels "0,0;1,0;2,0;3,0;4,0;5,0"
seta use_ff "1"
seta s_soundpoolmegs "25"
seta s_UseOpenAL "0"
seta s_mp3overhead "31756"
seta s_language "deutsch"
seta s_mixPreStep "0.05"
seta s_mixahead "0.2"
seta s_allowDynamicMusic "1"
seta s_khz "22"
seta s_separation "0.5"
seta s_musicvolume "0.25"
seta s_volumeVoice "1.0"
seta s_volume "0.5"
seta vid_ypos "22"
seta vid_xpos "3"
seta r_lastValidRenderer "GeForce GTX 285/PCI/SSE2"
seta r_modelpoolmegs "20"
seta r_showtriscolor "0"
seta r_primitives "0"
seta r_facePlaneCull "1"
seta r_gamma "1"
seta r_swapInterval "0"
seta r_textureMode "GL_LINEAR_MIPMAP_LINEAR"
seta r_finish "0"
seta r_dlightBacks "1"
seta r_dynamiclight "1"
seta r_drawSun "0"
seta r_fastsky "0"
seta r_ignoreGLErrors "1"
seta r_lodscale "10"
seta r_flares "1"
seta r_lodbias "0"
seta r_lodCurveError "250"
seta r_intensity "1"
seta r_ignoreFastPath "1"
seta r_subdivisions "4"
seta r_vertexLight "0"
seta r_simpleMipMaps "1"
seta r_customaspect "1"
seta r_customheight "1024"
seta r_customwidth "1600"
seta r_fullscreen "1"
seta r_mode "3"
seta r_ignorehwgamma "0"
seta r_overBrightBits "1"
seta r_depthbits "0"
seta r_stencilbits "8"
seta r_stereo "1"
seta r_colorbits "0"
seta r_texturebitslm "0"
seta r_texturebits "0"
seta r_detailtextures "1"
seta r_picmip "1"
seta r_ext_texture_filter_anisotropic "1"
seta r_ext_texture_env_add "1"
seta r_ext_compiled_vertex_array "1"
seta r_ext_multitexture "1"
seta r_ext_gamma_control "1"
seta r_ext_preferred_tc_method "0"
seta r_ext_compress_lightmaps "0"
seta r_ext_compress_textures "1"
seta r_allowExtensions "1"
seta handicap "100"
seta sex "male"
seta snaps "20"
seta name "Kyle"
seta m_filter "0"
seta m_side "0.25"
seta m_forward "0.25"
seta m_yaw "0.022"
seta m_pitch "0.022"
seta cg_autoswitch "1"
seta cl_VideoQuality "0"
seta cl_ingameVideo "1"
seta cl_freelook "1"
seta cl_mouseAccel "0"
seta sensitivity "5"
seta cl_run "1"
seta cl_packetdup "1"
seta cl_maxpackets "30"
seta cl_anglespeedkey "1.5"
seta cl_pitchspeed "140"
seta cl_yawspeed "140"
seta panoNumShots "10"
seta conAlpha "1.6"
seta joy_ybutton "0"
seta joy_xbutton "1"
seta js_ffmult "3.0"
seta joy_threshold "0.15"
seta in_joyBallScale "0.02"
seta in_joystick "0"
seta in_mouse "-1"
seta in_mididevice "0"
seta in_midichannel "1"
seta in_midiport "1"
seta in_midi "0"
seta sp_language "2"
seta com_maxfps "85"
seta ui_r_glCustom "4"

**Comment by Midnightmaster** [comment]
addendum:
Do I have to compile anything? And if so, how? Like most, I have no idea about C-Compilers. I have Win10 and the Steam version and using this file:
JediOutcast_VR_Binary_Win32_v1.1.0.1.zip

**Comment by jlmip** [comment]
We never released a version with the very experimental touch version.

There is a very outdated "how to build" text, but if you have no experience with cmake and VisualStudio, it might not be that easy for you to build it on your own.
https://github.com/xLAva/JediOutcastLinux/blob/VR-Touch/BUILD.md

I'm rather busy with other stuff at the moment, but I hope I get some time early next year to actually do some work on the project.

**Comment by xLAva** [comment]
We never released a version with the very experimental touch version.

There is a very outdated "how to build" text, but if you have no experience with cmake and VisualStudio, it might not be that easy for you to build it on your own.
https://github.com/xLAva/JediOutcastLinux/blob/VR-Touch/BUILD.md

I'm rather busy with other stuff at the moment, but I hope I get some time early next year to actually do some work on the project.

**Comment by Midnightmaster** [comment]
Thanks for your answer, maybe I'll deal with the compile times if I have more time. However, do not understand what is difficult as a developer to publish the already compiled version anyway. It does not make any sense to torture hundreds of users to work through it, if you can just upload it. I think that many programmers do not realize that maybe 0.01% of the user experiences with it and all the others are forced to give up the program, because they do not have the knowledge to do something like that. Many developers on Github publish alpha versions often only in the forum with the note that it is just alpha to test ...

**Comment by Midnightmaster** [comment]
Thanks for your answer, maybe I'll deal with the compiling if I have more time. However, i do not understand what is difficult as a developer to publish the already compiled version anyway. It does not make any sense to torture hundreds of users to work through it, if you can just upload it. I think that many programmers do not realize that maybe 0.01% of the user experiences with it and all the others are forced to give up the program, because they do not have the knowledge to do something like that. Many developers on Github publish alpha versions often only in the forum with the note that it is just alpha to test ...

**Comment by xLAva** [comment]
We do this in our free time for fun.
So we have no obligations to do anything.

And releasing a binary is more work than just uploading an executable.
Without some kind of documentation along side it, it is useless.
And also it should at least be roughly tested to make sure it is not totally broken.

It also has to be build from a clean base - we programmers often have some unfinished code active that is not yet committed - and we don't want the binary to be based on that state of code.

All I'm saying is - it is not a 5 second thing, but might as well take some hours to do.
And as I said before - this is a project we do for fun - and if we don't have the time to do it or just don't want to spend our little free time on it - you have to live with that.

**Comment by Midnightmaster** [comment]
Still do not understand, which is so hard to upload the compiled files here. I can only do what is in the manual and then have just a few files. I could spend a few hours working on it, compile the project and then post it here. But I'm pretty sure that this would be the same files that you as developers already have in any folder. I think that a developer has his own project compiled at one time or another. Packing and uploading a few files takes less time than writing this. But do not get me wrong, I'm very impressed with the project and I know what it takes to work on it.
