### ISSUE TITLE
Compiling problems on manjaro

### ISSUE THREAD

**Issue by darkstar252** [xLAva/JediOutcastLinux#84]
I have this problem trying to build the program: 

[ 11%] Building CXX object CMakeFiles/jk2gamex86.dir/code/cgame/cg_main.cpp.o
In file included from /usr/include/c++/8.1.1/map:61,
                 from /home/darkstar/JediOutcastLinux/code/cgame/../game/../game/ghoul2_shared.h:11,
                 from /home/darkstar/JediOutcastLinux/code/cgame/../game/q_shared.h:1112,
                 from /home/darkstar/JediOutcastLinux/code/cgame/cg_local.h:4,
                 from /home/darkstar/JediOutcastLinux/code/cgame/cg_headers.h:3,
                 from /home/darkstar/JediOutcastLinux/code/cgame/cg_main.cpp:2:
/usr/include/c++/8.1.1/bits/stl_map.h: En la instanciación de ‘class std::map<sstring<64>, unsigned char, std::less<sstring<64> >, std::allocator<unsigned char> >’:
/home/darkstar/JediOutcastLinux/code/cgame/cg_main.cpp:684:16:   se requiere desde aquí
/usr/include/c++/8.1.1/bits/stl_map.h:122:21: error: falló la aserción estática: std::map must have the same value_type as its allocator
       static_assert(is_same<typename _Alloc::value_type, value_type>::value,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/jk2gamex86.dir/build.make:453: CMakeFiles/jk2gamex86.dir/code/cgame/cg_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/jk2gamex86.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by xLAva** [comment]
I made a quick fix in this branch:
https://github.com/xLAva/JediOutcastLinux/tree/GCC8_CompileFix
Please test it out.

If it works for you I will integrate it in the main branch, once it also passes some tests on Ubuntu and Windows.

**Comment by darkstar252** [comment]
Thank you very much!! I have a question... if i want compile jk2mp? It's possible to compile in your sources??

**Comment by darkstar252** [comment]
And it works compiles perfectly. Thanks!!

**Comment by xLAva** [comment]
The multiplayer code is still the original one. I did not touch it. So it won't compile on Linux.

**Comment by darkstar252** [comment]
I think there is a good idea to touch it and add in the single player code, a funcionality to play the music in mp3/ogg format instead from the original CD-ROM.
