### ISSUE TITLE
Linux : mouse wheel binding regression since SDL2 ?

### ISSUE THREAD

**Issue by ThibaultMndr** [xLAva/JediOutcastLinux#86]
Mouse wheel binding worked in linux non-VR binary release, but not when compiling from latest sources. 

I tryed to un-comment existing code in sdl_glimp.cpp (from line 1532) and it worked for me (on Archlinux) : 

```
//        case SDL_MOUSEWHEEL:        
//            if (event.wheel.y != 0)
//            {
//                int wheel = event.wheel.y < 0 ? A_MWHEELDOWN : A_MWHEELUP;
//                //VID_Printf (PRINT_ALL, "wheel.y=%d\n", event.wheel.y);
                
//                int wheelCount = abs(event.wheel.y);
//                for (int i=0; i<wheelCount; i++)
//                {
//                    QueKeyEvent( 0, SE_KEY, wheel, qtrue, 0, NULL );
//                    QueKeyEvent( 0, SE_KEY, wheel, qfalse, 0, NULL );
//                }
               
//            }
//            break;
```
I think this code has been disabled for a good reason but which one ?

Regards,

**Comment by xLAva** [comment]
I checked the logs to see why I commented it, but it looked that way from the first commit.
I just can't remember if there was a reason for this or if this was just a mistake.

If my test work as well I will uncomment it.
Thx for the info!

**Comment by xLAva** [comment]
Fixed it in the latest commit.
Thx again.
