### ISSUE TITLE
Problem since steamVR update

### ISSUE THREAD

**Issue by TyXe0** [xLAva/JediOutcastLinux#87]
Hello,
I have a problem, I think since the update of steamVR.

The screen on the left eye is flickering the whole time and right eye is black.

Maybe soluce or update ?

Thanks you :)

**Comment by TyXe0** [comment]
Ok, problem resolved for now, I downgrade steam VR to the version 1.2.10

**Comment by xLAva** [comment]
Should be fixed in #89

**Comment by TyXe0** [comment]
Thx ! :)
