### ISSUE TITLE
Constantly crashing as soon as you enter level

### ISSUE THREAD

**Issue by KuraiShidosha** [xLAva/JediOutcastLinux#88]
Hi I'm having a major problem with the VR branches. I can see the game in the headset, headtracking presumably works, but as soon as I load a level and go to skip the cutscene, it crashes with the following error in Event Viewer:

Faulting application name: jk2sp.exe, version: 0.0.0.0, time stamp: 0x5a7cb9ae
Faulting module name: jk2gamex86.dll, version: 0.0.0.0, time stamp: 0x5a7cb9d7
Exception code: 0xc0000005
Fault offset: 0x00040620

I really don't know what I'm doing wrong. Any suggestions?

**Comment by xLAva** [comment]
Did you compile the game yourself or did you use binary files?
And if you used binaries, which one did you try?

**Comment by KuraiShidosha** [comment]
The latest VR Touch binaries as of the writing of that issue.

**Comment by xLAva** [comment]
Hmm - strange.
Do the binaries without VR support work for you?

**Comment by KuraiShidosha** [comment]
I don't think they worked at all where the VR Touch branch at least rendered properly at the main menu. I had a Vive at the time so not sure if that's relevant.

**Comment by xLAva** [comment]
I don't have a Vive myself, so I can't say for sure if there might be a bug in how we initialize the headset.
Since I'm missing the hardware, I'm afraid I can't help you right now.
I will keep this bug open and lookout for anything that could cause this issue.

**Comment by KuraiShidosha** [comment]
Thanks. I'll be getting an Index in a few weeks and will try again then. I returned my Vive so I cannot do any testing until then, but since both use the same SteamVR API, it should have similar outcomes.

**Comment by xLAva** [comment]
I just updated the binaries. Please try again with the new one. Thx.

**Comment by KuraiShidosha** [comment]
Ok I have my Index headset now and I tried the latest binaries. Couldn't get anything but gray screen to the VR headset and the game runs in a massive window on my desktop. If I had to guess it's being ran in windowed mode with my DSR 4x resolution of 5120x2880 on my 2560x1440 monitor. I'm wondering if it might be because of updated Oculus runtime binaries. I only have older ones from August 2018. SteamVR detects the game is trying to run in VR but it pretty much gets stuck at the main menu.

If you have the latest Oculus binaries, could you upload them both the 32 and 64 bit ones, to a repository somewhere so I can see if that fixes the problem? I don't install the full Oculus software package (all 7GB straight to my SSD) for what ultimately only provides 2 dll files worth not even 5MB between the two of them.

**Comment by xLAva** [comment]
If I'm understanding this right - you got a totally new headset - the Valve Index.
Please open a new bug report for that, since it has nothing to do with the original crash on entering a level.

And since it is a Valve headset, it has nothing to do witch Oculus so you don't need any Oculus binary files for that headset.

**Comment by KuraiShidosha** [comment]
I'm not sure if you're familiar with this or not, but the Valve Index uses the same SteamVR API as the Vive I used to report the error initially 3 months ago.

The reason we need Oculus binaries is because IIRC this mod does not natively support SteamVR and thus users had to use Revive in order to translate Oculus runtime calls to SteamVR ones. For many users this worked flawlessly back when the mod was initially released and as recent as late 2018. But I suspect changes made to SteamVR and perhaps Oculus runtimes too, have impacted support of the game along the way. My initial report is that as of April 2019, the originally functioning setup of JK2 VR on a Vive did not work anymore. That is still true today, with the Index. They are interchangeable from a API standpoint. If an application works on one, it works on the other. If an application does not work on one, it does not work on the other. That's where we're at right now.

I understand if this convolutes things for you and if you no longer wish to pursue support for this, I'd understand. But know that there are many, many fans out there who would be happy to support you and see this mod updated with better device and API compatibility.

**Comment by xLAva** [comment]
You are mistaken. We have native SteamVR support over OpenVR since beginning of last year.
So as I said - no Oculus hacks needed.

And it is still a different bug as you don't experience a crash.
I'm hard on this point, because I'm pretty sure the crash bug was fixed.
I wished we could have verified this, but since you don't have the same setup anymore we won't be able to.

The new issue, that the Index does not work, does not surprise me. I'm pretty sure the OpenVR version is just too old to work with this brand new headset. Also we never tested it with it.

It is wishful thinking that everything just works out of the box  and is compatible for new hardware without tweaking stuff in code. In my experience (and I had all the different Oculus hardware to work with), tweaks are always needed.

**Comment by KuraiShidosha** [comment]
I deeply apologize for the confusion and misinformation. I was wrongly assuming this mod did not natively support SteamVR headsets. Since learning this just now, I deleted all Revive hacks and Oculus runtimes, verified the game cache on Steam, simply copy pasted the latest binaries and everything works flawlessly on the Index. No more crashing on level load. This issue can now be closed :) thank you again for your support and your patience with this noob of a fan!

**Comment by xLAva** [comment]
I'm glad to hear that i actually works out of the box!
Have fun! :-)
