### ISSUE TITLE
Right eye shows nothing, left eye flashing - VR Touch branch

### ISSUE THREAD

**Issue by ditchmagnet** [xLAva/JediOutcastLinux#90]
I had it working on my Rift S with touch support, I don't know what happened, but now I'm getting the issue in my title.

Is there something I can do for this?

EDIT: The Rift S works fine in the regular VR version.

**Comment by xLAva** [comment]
Did you compile it yourself or did you use a binary.
If you use a binary, which one did you use?

**Comment by xLAva** [comment]
I just changed the initialization process.
The OculusSDK is prefered over the OpenVR library. It should work now in all cases for Oculus hardware again.
Please try again.

**Comment by ditchmagnet** [comment]
Ok I'll try it out. Yes, I was using the binary win32. I think it was the only one in vrtouch. I'll report back my results with the new one. Thank!

**Comment by ditchmagnet** [comment]
Great, it's working now! Thanks so much! Also is working on through steamVR on my WMR headset!
